version: "2"

services:
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: "10m"

  db:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
