services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    expose:
      - "9000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  webserver:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - .:/var/www/html:ro
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      UPLOAD_LIMIT: 64M
