# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'  # Trigger only on changes in the admin folder

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env: 
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files
        run: |
          ls -R
          echo "Current directory: $(pwd)"
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./admin  # Define o diretório de trabalho para admin

      - name: Build
        run: npm run build
        working-directory: ./admin  # Define o diretório de trabalho para admin

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './admin/dist'  # Upload da pasta dist dentro de admin

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
